baseURL = "https://quqiuzhu.com/"
languageCode = "zh-CN"
title = "看见未来"
theme = "custom-from-hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-140819128-1"

[permalinks]
  posts = "/:year/:filename/"


[params]
    author = "屈秋竹"
    info = "视频工程师"
    description = "屈秋竹的个人网站"
    keywords = "屈秋竹,秋竹,程序员,站长,工程师,商汤,虎牙,音视频,看见未来"
    avatarurl = "avatar.png"

    favicon_32 = "favicon.png"
    favicon_16 = "favicon.png"

    footercontent = "浙ICP备17015868号"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true


# Utterances
[params.utter]
    repo = "quqiuzhu/quqiuzhu.github.io"
    issueTerm = "title" # pathname title url
    theme = "github-light"


# Social links
[[params.social]]
    name = "Github"
    icon = "icon-github"
    weight = 1
    url = "https://github.com/quqiuzhu/"

[[params.social]]
    name = "LinkedIn"
    icon = "icon-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/quqiuzhu/"

[[params.social]]
    name = "Email"
    icon = "icon-mail-open"
    weight = 3
    url = "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=WSgsKDAsIzEsGSgodzo2NA"

[[params.social]]
    name = "RSS"
    icon = "icon-rss"
    weight = 4
    url = "/index.xml"


# Menu links
[[menu.main]]
    name = "博客"
    weight = 1
    url  = "/posts/"

[[menu.main]]
    name = "关于"
    weight = 2
    url = "/about/"
